#!/usr/bin/env bash
# Point this checkout at AdithyaPatil-1609/pagecrafts for all `gh` PR/issue
# commands, while keeping origin as the HSA2005-cloud fork for push.
#
# Cloud agents clone the fork. Production and the real PR target are upstream.
# Run from install/start (and any new shell) so the default cannot drift.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

UPSTREAM_REPO="AdithyaPatil-1609/pagecrafts"
UPSTREAM_URL="https://github.com/${UPSTREAM_REPO}.git"
ENV_FILE="${HOME}/.config/pagecrafts/upstream.env"

if git remote get-url upstream >/dev/null 2>&1; then
  git remote set-url upstream "$UPSTREAM_URL"
else
  git remote add upstream "$UPSTREAM_URL"
fi

# `gh pr create`, `gh pr list`, etc. resolve here — not to the fork.
if command -v gh >/dev/null 2>&1; then
  gh repo set-default "$UPSTREAM_REPO" >/dev/null
fi

mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-upstream-default.sh — do not edit by hand.
export GH_REPO="${UPSTREAM_REPO}"
EOF

# Persist for interactive and agent shells in this environment.
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  touch "$rc"
  if ! grep -qF 'pagecrafts/upstream.env' "$rc" 2>/dev/null; then
    printf '\n# pagecrafts: default gh target is upstream (AdithyaPatil-1609/pagecrafts)\n[ -f "%s" ] && . "%s"\n' \
      "$ENV_FILE" "$ENV_FILE" >> "$rc"
  fi
done

# Current shell (when sourced or run under bash -c with export).
export GH_REPO="$UPSTREAM_REPO"

echo "Default PR target: ${UPSTREAM_REPO}"
command -v gh >/dev/null && gh repo set-default --view || true
