#!/usr/bin/env bash
# Make AdithyaPatil-1609/pagecrafts the source of truth for this checkout.
#
# - Pull / fetch default to the ORIGINAL repo (AdithyaPatil-1609/pagecrafts).
# - `gh` defaults to the ORIGINAL repo (PRs, issues, checks).
# - Push: cursor[bot] cannot write to the original repo (403). Branches are
#   pushed to the fork remote (`fork` / push-url of `origin`) so a human can
#   open or merge a PR into the original. Prefer `scripts/pr-original.sh`.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

ORIGINAL_OWNER="AdithyaPatil-1609"
ORIGINAL_REPO="AdithyaPatil-1609/pagecrafts"
ORIGINAL_URL="https://github.com/${ORIGINAL_REPO}.git"
FORK_OWNER="HSA2005-cloud"
FORK_REPO="HSA2005-cloud/pagecrafts"
ENV_FILE="${HOME}/.config/pagecrafts/original-repo.env"

# Keep whatever token the cloud agent already attached to remotes (if any).
current_origin="$(git remote get-url origin 2>/dev/null || true)"
current_upstream="$(git remote get-url upstream 2>/dev/null || true)"
token=""
if [[ "$current_origin" =~ x-access-token:([^@]+)@ ]]; then
  token="${BASH_REMATCH[1]}"
elif [[ "$current_upstream" =~ x-access-token:([^@]+)@ ]]; then
  token="${BASH_REMATCH[1]}"
fi

auth_url() {
  local repo="$1"
  if [ -n "$token" ]; then
    printf 'https://x-access-token:%s@github.com/%s.git' "$token" "$repo"
  else
    printf 'https://github.com/%s.git' "$repo"
  fi
}

ORIGINAL_FETCH="$(auth_url "$ORIGINAL_REPO")"
FORK_PUSH="$(auth_url "$FORK_REPO")"

# origin: FETCH from original (so `git pull` / `git fetch origin` = original).
#         PUSH to fork (only writable remote for this agent).
if git remote get-url origin >/dev/null 2>&1; then
  git remote set-url origin "$ORIGINAL_FETCH"
  git remote set-url --push origin "$FORK_PUSH"
else
  git remote add origin "$ORIGINAL_FETCH"
  git remote set-url --push origin "$FORK_PUSH"
fi

# upstream: always the original (fetch + push URL both original; push will 403
# for cursor[bot], which is intentional — use a PR instead).
if git remote get-url upstream >/dev/null 2>&1; then
  git remote set-url upstream "$ORIGINAL_FETCH"
  git remote set-url --push upstream "$ORIGINAL_FETCH"
else
  git remote add upstream "$ORIGINAL_FETCH"
fi

# Explicit fork remote for `git push -u fork HEAD`.
if git remote get-url fork >/dev/null 2>&1; then
  git remote set-url fork "$FORK_PUSH"
  git remote set-url --push fork "$FORK_PUSH"
else
  git remote add fork "$FORK_PUSH"
fi

# Prefer original when a branch name exists on multiple remotes.
git config checkout.defaultRemote origin
git config --local "branch.main.remote" origin
git config --local "branch.main.merge" refs/heads/main

# gh / GH_REPO always the original — never the fork.
if command -v gh >/dev/null 2>&1; then
  gh repo set-default "$ORIGINAL_REPO" >/dev/null 2>&1 || true
fi

mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-original-repo.sh — do not edit by hand.
export GH_REPO="${ORIGINAL_REPO}"
export PAGECRAFTS_ORIGINAL_REPO="${ORIGINAL_REPO}"
export PAGECRAFTS_FORK_OWNER="${FORK_OWNER}"
export PAGECRAFTS_ORIGINAL_OWNER="${ORIGINAL_OWNER}"
EOF

for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  touch "$rc"
  if ! grep -qF 'pagecrafts/original-repo.env' "$rc" 2>/dev/null; then
    # Drop the older upstream.env hook if present.
    if grep -qF 'pagecrafts/upstream.env' "$rc" 2>/dev/null; then
      tmp="$(mktemp)"
      grep -vF 'pagecrafts/upstream.env' "$rc" > "$tmp" || true
      mv "$tmp" "$rc"
    fi
    printf '\n# pagecrafts: original repo is AdithyaPatil-1609/pagecrafts\n[ -f "%s" ] && . "%s"\n' \
      "$ENV_FILE" "$ENV_FILE" >> "$rc"
  fi
done

export GH_REPO="$ORIGINAL_REPO"
export PAGECRAFTS_ORIGINAL_REPO="$ORIGINAL_REPO"
export PAGECRAFTS_FORK_OWNER="$FORK_OWNER"
export PAGECRAFTS_ORIGINAL_OWNER="$ORIGINAL_OWNER"

echo "Original repo (pull / gh default): ${ORIGINAL_REPO}"
echo "Fork (branch push only):           ${FORK_REPO}"
echo "origin fetch -> original, origin push -> fork"
command -v gh >/dev/null && gh repo set-default --view 2>/dev/null || true
